### ISSUE TITLE
p5.window_width is not available in setup(), but is in draw()

### ISSUE THREAD

**Issue by adamantonio** [nickmcintyre/proceso#2]
Attempting to create a canvas the size of the browser viewport fails due to `window_width` and `window_height` not being available in setup:
```
def setup():
    p5.create_canvas(p5.window_width, p5.window_height)
```

Reported error message:
> Traceback (most recent call last):
>   File "/lib/python311.zip/_pyodide/_base.py", line 499, in eval_code
>     .run(globals, locals)
>      ^^^^^^^^^^^^^^^^^^^^
>   File "/lib/python311.zip/_pyodide/_base.py", line 340, in run
>     coroutine = eval(self.code, globals, locals)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<exec>", line 15, in <module>
>   File "/lib/python3.11/site-packages/proceso/binding.py", line 102, in run_sketch
>     self._p5js._start()
>   File "https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.8.0/p5.min.js", line 2, in g._start
>   File "https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.8.0/p5.min.js", line 2, in g._setup
>   File "<exec>", line 7, in setup
> AttributeError: 'Sketch' object has no attribute 'window_width'

The properties are available in draw(), so a workaround is to call `resize_canvas()` there:
```
def setup():
    pass    

def draw():
    p5.resize_canvas(p5.window_width, p5.window_height)
    p5.background("crimson")
```

**Comment by adamantonio** [comment]
Calling `_update_system_variables()` before `run_sketch()` solves the problem. So this works:

```
def setup():
    p5.create_canvas(p5.window_width, p5.window_height)

def draw():
    p5.background("crimson")

p5._update_system_variables()    # Fix to allow setup to create a fullscreen canvas
p5.run_sketch(setup=setup, draw=draw)
```

**Comment by nickmcintyre** [comment]
Thanks for catching this @adamantonio!

I just pushed a fix to PyPI. `Sketch.__init__()` now calls `this._update_system_variables()`. Let me know if that works.

**Comment by adamantonio** [comment]
Looks good, thank you!
